steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_REPO:$_TAG', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_REPO:$_TAG']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_IMAGE_REPO:$_TAG
      - --region=$_REGION
      - --platform=managed
      - --quiet
      - --set-env-vars=MODE=mvp,STUB_MODE=false,USE_REFACTORED_SUMMARISER=true,SUMMARY_COMPOSE_MODE=refactored,PDF_WRITER_MODE=rich,ENABLE_NOISE_FILTERS=true,SUPERVISOR_MODE=simple,DRIVE_ENABLED=true,WRITE_TO_DRIVE=true,PDF_ENABLED=true,SHEETS_ENABLED=false,ENABLE_METRICS=true,PROJECT_ID=$_PROJECT_ID,REGION=$_REGION,DOC_AI_LOCATION=$_DOC_AI_LOCATION,DOC_AI_PROCESSOR_ID=$_DOC_AI_PROCESSOR_ID,DOC_AI_OCR_PROCESSOR_ID=$_DOC_AI_PROCESSOR_ID,DRIVE_INPUT_FOLDER_ID=$_DRIVE_INPUT_FOLDER_ID,DRIVE_REPORT_FOLDER_ID=$_DRIVE_REPORT_FOLDER_ID,DRIVE_SHARED_DRIVE_ID=$_DRIVE_SHARED_DRIVE_ID,CMEK_KEY_NAME=$_CMEK_KEY_NAME,INTAKE_GCS_BUCKET=$_INTAKE_BUCKET,OUTPUT_GCS_BUCKET=$_OUTPUT_BUCKET,SUMMARY_BUCKET=$_SUMMARY_BUCKET,DRIVE_IMPERSONATION_USER=$_DRIVE_IMPERSONATION_USER,GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-application-credentials.json,MIN_SUMMARY_CHARS=300,MIN_SUMMARY_DYNAMIC_RATIO=0.005
      - --remove-secrets=GOOGLE_APPLICATION_CREDENTIALS
      - --service-account=$_SERVICE_ACCOUNT
      - --update-secrets=OPENAI_API_KEY=$_OPENAI_API_SECRET:latest,SERVICE_ACCOUNT_JSON=$_SERVICE_ACCOUNT_SECRET:latest,INTERNAL_EVENT_TOKEN=$_INTERNAL_EVENT_TOKEN_SECRET:latest

substitutions:
  _TAG: v11mvp
  _IMAGE_REPO: us-central1-docker.pkg.dev/your-gcp-project-id/mcc/mcc-ocr-summary
  _SERVICE_NAME: mcc-ocr-summary
  _SERVICE_ACCOUNT: orchestrator-sa@your-gcp-project-id.iam.gserviceaccount.com
  _CMEK_KEY_NAME: projects/your-gcp-project/locations/LOCATION/keyRings/YOUR_KEYRING/cryptoKeys/YOUR_KEY
  _PROJECT_ID: your-gcp-project-id
  _REGION: us-central1
  _DOC_AI_LOCATION: us
  _DOC_AI_PROCESSOR_ID: your-docai-processor-id
  _INTAKE_BUCKET: your-intake-bucket
  _OUTPUT_BUCKET: your-output-bucket
  _SUMMARY_BUCKET: your-summary-bucket
  _DRIVE_INPUT_FOLDER_ID: your-drive-input-folder-id
  _DRIVE_REPORT_FOLDER_ID: your-drive-report-folder-id
  _DRIVE_SHARED_DRIVE_ID: your-drive-shared-drive-id
  _DRIVE_IMPERSONATION_USER: someone@example.com
  _OPENAI_API_SECRET: OPENAI_API_KEY
  _SERVICE_ACCOUNT_SECRET: service-account-json
  _INTERNAL_EVENT_TOKEN_SECRET: internal-event-token

images:
  - $_IMAGE_REPO:$_TAG
