steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_REPO:$_TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_REPO:$_TAG_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image=$_IMAGE_REPO:$_TAG_NAME
      - --region=$_REGION
      - --platform=managed
      - --quiet
      - --set-env-vars=MODE=mvp,STUB_MODE=false,USE_REFACTORED_SUMMARISER=true,SUMMARY_COMPOSE_MODE=$_SUMMARY_COMPOSE_MODE,PDF_WRITER_MODE=$_PDF_WRITER_MODE,PDF_GUARD_ENABLED=$_PDF_GUARD_ENABLED,ENABLE_NOISE_FILTERS=true,SUPERVISOR_MODE=simple,DRIVE_ENABLED=true,WRITE_TO_DRIVE=true,PDF_ENABLED=true,SHEETS_ENABLED=false,ENABLE_METRICS=true,PROJECT_ID=$_PROJECT_ID,REGION=$_REGION,TAG_NAME=$_TAG_NAME,DOC_AI_LOCATION=$_DOC_AI_LOCATION,DOC_AI_PROCESSOR_ID=$_DOC_AI_PROCESSOR_ID,DOC_AI_OCR_PROCESSOR_ID=$_DOC_AI_PROCESSOR_ID,DRIVE_INPUT_FOLDER_ID=$_DRIVE_INPUT_FOLDER_ID,DRIVE_REPORT_FOLDER_ID=$_DRIVE_REPORT_FOLDER_ID,PDF_INPUT_FOLDER_ID=$_PDF_INPUT_FOLDER_ID,PDF_OUTPUT_FOLDER_ID=$_PDF_OUTPUT_FOLDER_ID,DRIVE_SHARED_DRIVE_ID=$_DRIVE_SHARED_DRIVE_ID,CMEK_KEY_NAME=$_CMEK_KEY_NAME,INTAKE_GCS_BUCKET=$_INTAKE_BUCKET,OUTPUT_GCS_BUCKET=$_OUTPUT_BUCKET,SUMMARY_BUCKET=$_SUMMARY_BUCKET,DRIVE_IMPERSONATION_USER=$_DRIVE_IMPERSONATION_USER,GOOGLE_APPLICATION_CREDENTIALS=/tmp/google-application-credentials.json,MIN_SUMMARY_CHARS=300,MIN_SUMMARY_DYNAMIC_RATIO=0.005
      - --remove-secrets=GOOGLE_APPLICATION_CREDENTIALS
      - --service-account=$_SERVICE_ACCOUNT
      - --update-secrets=OPENAI_API_KEY=$_OPENAI_API_SECRET:latest,SERVICE_ACCOUNT_JSON=$_SERVICE_ACCOUNT_SECRET:latest,INTERNAL_EVENT_TOKEN=$_INTERNAL_EVENT_TOKEN_SECRET:latest

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        if [ -z "$_VALIDATION_CREDENTIALS_SECRET" ]; then
          echo "Skipping summary validator step; _VALIDATION_CREDENTIALS_SECRET not configured."
          exit 0
        fi
        export PIP_BREAK_SYSTEM_PACKAGES=1
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt -c constraints.txt
        gcloud secrets versions access latest --secret="$_VALIDATION_CREDENTIALS_SECRET" > validator-sa.json
        if [ -n "$_VALIDATION_IMPERSONATE" ]; then
          IMPERSONATE_ARG="--impersonate $_VALIDATION_IMPERSONATE"
        else
          IMPERSONATE_ARG=""
        fi
        python3 scripts/validate_summary.py \
          --base-url "$_VALIDATION_BASE_URL" \
          --source-file-id "$_VALIDATION_SOURCE_FILE_ID" \
          --expected-pages 263 \
          --credentials validator-sa.json \
          $$IMPERSONATE_ARG
        rm -f validator-sa.json

substitutions:
  _TAG_NAME: v11mvp
  _IMAGE_REPO: us-central1-docker.pkg.dev/quantify-agent/mcc/mcc-ocr-summary
  _SERVICE_NAME: mcc-ocr-summary
  _SERVICE_ACCOUNT: mcc-orch-sa@quantify-agent.iam.gserviceaccount.com
  _CMEK_KEY_NAME: projects/quantify-agent/locations/us-central1/keyRings/mcc-phi/cryptoKeys/mcc-phi-key
  _PROJECT_ID: quantify-agent
  _REGION: us-central1
  _DOC_AI_LOCATION: us
  _DOC_AI_PROCESSOR_ID: 21c8becfabc49de6
  _INTAKE_BUCKET: mcc-intake
  _OUTPUT_BUCKET: mcc-output
  _SUMMARY_BUCKET: mcc-output
  _DRIVE_INPUT_FOLDER_ID: 1eyMO0126VfLBK3bBQEpWlVOL6tWxriCE
  _DRIVE_REPORT_FOLDER_ID: 130jJzsl3OBzMD8weGfBOaXikfEnD2KVg
  _PDF_INPUT_FOLDER_ID: 1eyMO0126VfLBK3bBQEpWlVOL6tWxriCE
  _PDF_OUTPUT_FOLDER_ID: 130jJzsl3OBzMD8weGfBOaXikfEnD2KVg
  _DRIVE_SHARED_DRIVE_ID: 0AFPP3mbSAh_oUk9PVA
  _DRIVE_IMPERSONATION_USER: Matt@moneymediausa.com
  _OPENAI_API_SECRET: OPENAI_API_KEY
  _SERVICE_ACCOUNT_SECRET: mcc_orch_sa_key
  _INTERNAL_EVENT_TOKEN_SECRET: internal-event-token
  _SUMMARY_COMPOSE_MODE: refactored
  _PDF_WRITER_MODE: rich
  _PDF_GUARD_ENABLED: 'true'
  _VALIDATION_BASE_URL: https://mcc-ocr-summary-6vupjpy5la-uc.a.run.app
  _VALIDATION_SOURCE_FILE_ID: 1ZFra9EN0jS8wTS4dcW7deypxnVggb8vS
  _VALIDATION_CREDENTIALS_SECRET: validator-sa-key
  _VALIDATION_IMPERSONATE: ''

images:
  - '$_IMAGE_REPO:$_TAG_NAME'
