apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcc-ocr-summary
  namespace: default
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/client-name: "gcloud"
    spec:
      containers:
        # App container
        - name: app
          image: us-central1-docker.pkg.dev/quantify-agent/mcc/mcc-orchestrator:latest
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
        # Managed Service for Prometheus sidecar
        - name: gmp-sidecar
          image: gcr.io/cloudrun/managed-prometheus-sidecar:latest
          env:
            - name: TARGET
              value: "http://localhost:8080/metrics"
            - name: PROJECT_ID
              value: "quantify-agent"
      containerConcurrency: 4
      timeoutSeconds: 1200
