#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="mcc-ocr-summary"
REGION="${REGION:-us-central1}"
PROJECT="${PROJECT_ID:?PROJECT_ID env var required}"
IMAGE="gcr.io/$PROJECT/$SERVICE_NAME:$(git rev-parse --short HEAD)"
APP_VERSION="v11h-$(git rev-parse --short HEAD)"
MODE_VALUE="${MODE:-mvp}"
STUB_MODE_VALUE="${STUB_MODE:-false}"
WRITE_TO_DRIVE_VALUE="${WRITE_TO_DRIVE:-true}"
DOC_AI_LOCATION="${DOC_AI_LOCATION:-us}"
DOC_AI_PROCESSOR_ID="${DOC_AI_PROCESSOR_ID:?DOC_AI_PROCESSOR_ID env var required}"
DRIVE_INPUT_FOLDER_ID="${DRIVE_INPUT_FOLDER_ID:?DRIVE_INPUT_FOLDER_ID env var required}"
DRIVE_REPORT_FOLDER_ID="${DRIVE_REPORT_FOLDER_ID:?DRIVE_REPORT_FOLDER_ID env var required}"
DRIVE_SHARED_DRIVE_ID="${DRIVE_SHARED_DRIVE_ID:?DRIVE_SHARED_DRIVE_ID env var required}"
DRIVE_IMPERSONATION_USER="${DRIVE_IMPERSONATION_USER:?DRIVE_IMPERSONATION_USER env var required}"
CMEK_KEY_NAME="${CMEK_KEY_NAME:?CMEK_KEY_NAME env var required}"
GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-/secrets/mcc_orch_sa_key.json}"
INTAKE_GCS_BUCKET="${INTAKE_GCS_BUCKET:?INTAKE_GCS_BUCKET env var required}"
OUTPUT_GCS_BUCKET="${OUTPUT_GCS_BUCKET:?OUTPUT_GCS_BUCKET env var required}"
SUMMARY_BUCKET="${SUMMARY_BUCKET:?SUMMARY_BUCKET env var required}"

echo "Building image: $IMAGE" >&2
gcloud builds submit --tag "$IMAGE" .

echo "Deploying to Cloud Run: $SERVICE_NAME" >&2
gcloud run deploy "$SERVICE_NAME" \
  --image "$IMAGE" \
  --region "$REGION" \
  --platform managed \
  --no-allow-unauthenticated \
  --project "$PROJECT" \
  --timeout=600 \
  --memory=1Gi \
  --update-env-vars MODE="$MODE_VALUE",STUB_MODE="$STUB_MODE_VALUE",WRITE_TO_DRIVE="$WRITE_TO_DRIVE_VALUE",PROJECT_ID="$PROJECT",REGION="$REGION",DOC_AI_LOCATION="$DOC_AI_LOCATION",DOC_AI_PROCESSOR_ID="$DOC_AI_PROCESSOR_ID",DRIVE_INPUT_FOLDER_ID="$DRIVE_INPUT_FOLDER_ID",DRIVE_REPORT_FOLDER_ID="$DRIVE_REPORT_FOLDER_ID",DRIVE_SHARED_DRIVE_ID="$DRIVE_SHARED_DRIVE_ID",DRIVE_IMPERSONATION_USER="$DRIVE_IMPERSONATION_USER",CMEK_KEY_NAME="$CMEK_KEY_NAME",GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS",INTAKE_GCS_BUCKET="$INTAKE_GCS_BUCKET",OUTPUT_GCS_BUCKET="$OUTPUT_GCS_BUCKET",SUMMARY_BUCKET="$SUMMARY_BUCKET",APP_VERSION="${APP_VERSION}",USE_STRUCTURED_SUMMARISER="${USE_STRUCTURED_SUMMARISER:-true}" \
  --update-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest,INTERNAL_EVENT_TOKEN=internal-event-token:latest,SERVICE_ACCOUNT_JSON=mcc_orch_sa_key:latest,/secrets/mcc_orch_sa_key.json=mcc_orch_sa_key:latest \
  --command uvicorn --args "src.main:create_app --factory --host 0.0.0.0 --port 8080"

echo "Deployment complete." >&2
