#!/usr/bin/env bash
set -euo pipefail

SERVICE_NAME="mcc-ocr-summary"
REGION="${REGION:-us-central1}"
PROJECT="${PROJECT_ID:?PROJECT_ID env var required}"
IMAGE="gcr.io/$PROJECT/$SERVICE_NAME:$(git rev-parse --short HEAD)"
APP_VERSION="v11h-$(git rev-parse --short HEAD)"
MODE_VALUE="${MODE:-mvp}"
STUB_MODE_VALUE="${STUB_MODE:-false}"
WRITE_TO_DRIVE_VALUE="${WRITE_TO_DRIVE:-true}"
DOC_AI_LOCATION="${DOC_AI_LOCATION:-us}"
DOC_AI_PROCESSOR_ID="${DOC_AI_PROCESSOR_ID:?DOC_AI_PROCESSOR_ID env var required}"
DRIVE_INPUT_FOLDER_ID="${DRIVE_INPUT_FOLDER_ID:?DRIVE_INPUT_FOLDER_ID env var required}"
DRIVE_REPORT_FOLDER_ID="${DRIVE_REPORT_FOLDER_ID:?DRIVE_REPORT_FOLDER_ID env var required}"
PDF_INPUT_FOLDER_ID="${PDF_INPUT_FOLDER_ID:-$DRIVE_INPUT_FOLDER_ID}"
PDF_OUTPUT_FOLDER_ID="${PDF_OUTPUT_FOLDER_ID:-$DRIVE_REPORT_FOLDER_ID}"
DRIVE_SHARED_DRIVE_ID="${DRIVE_SHARED_DRIVE_ID:?DRIVE_SHARED_DRIVE_ID env var required}"
DRIVE_IMPERSONATION_USER="${DRIVE_IMPERSONATION_USER:?DRIVE_IMPERSONATION_USER env var required}"
CMEK_KEY_NAME="${CMEK_KEY_NAME:?CMEK_KEY_NAME env var required}"
GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-/secrets/orchestrator-sa-key.json}"
INTAKE_GCS_BUCKET="${INTAKE_GCS_BUCKET:?INTAKE_GCS_BUCKET env var required}"
OUTPUT_GCS_BUCKET="${OUTPUT_GCS_BUCKET:?OUTPUT_GCS_BUCKET env var required}"
SUMMARY_BUCKET="${SUMMARY_BUCKET:?SUMMARY_BUCKET env var required}"
OPENAI_API_SECRET_NAME="${OPENAI_API_SECRET_NAME:-OPENAI_API_KEY}"
INTERNAL_EVENT_SECRET_NAME="${INTERNAL_EVENT_SECRET_NAME:-internal-event-token}"
SERVICE_ACCOUNT_SECRET_NAME="${SERVICE_ACCOUNT_SECRET_NAME:-orchestrator-sa-key}"
GOOGLE_APPLICATION_CREDENTIALS_SECRET_NAME="${GOOGLE_APPLICATION_CREDENTIALS_SECRET_NAME:-orchestrator-sa-key}"
GOOGLE_APPLICATION_CREDENTIALS_MOUNT="${GOOGLE_APPLICATION_CREDENTIALS_MOUNT:-/secrets/orchestrator-sa-key.json}"

echo "Building image: $IMAGE" >&2
gcloud builds submit --tag "$IMAGE" .

echo "Deploying to Cloud Run: $SERVICE_NAME" >&2
gcloud run deploy "$SERVICE_NAME" \
  --image "$IMAGE" \
  --region "$REGION" \
  --platform managed \
  --no-allow-unauthenticated \
  --project "$PROJECT" \
  --timeout=600 \
  --memory=1Gi \
  --update-env-vars MODE="$MODE_VALUE",STUB_MODE="$STUB_MODE_VALUE",WRITE_TO_DRIVE="$WRITE_TO_DRIVE_VALUE",PROJECT_ID="$PROJECT",REGION="$REGION",DOC_AI_LOCATION="$DOC_AI_LOCATION",DOC_AI_PROCESSOR_ID="$DOC_AI_PROCESSOR_ID",DRIVE_INPUT_FOLDER_ID="$DRIVE_INPUT_FOLDER_ID",DRIVE_REPORT_FOLDER_ID="$DRIVE_REPORT_FOLDER_ID",PDF_INPUT_FOLDER_ID="$PDF_INPUT_FOLDER_ID",PDF_OUTPUT_FOLDER_ID="$PDF_OUTPUT_FOLDER_ID",DRIVE_SHARED_DRIVE_ID="$DRIVE_SHARED_DRIVE_ID",DRIVE_IMPERSONATION_USER="$DRIVE_IMPERSONATION_USER",CMEK_KEY_NAME="$CMEK_KEY_NAME",GOOGLE_APPLICATION_CREDENTIALS="$GOOGLE_APPLICATION_CREDENTIALS",SUMMARY_COMPOSE_MODE="refactored",PDF_WRITER_MODE="rich",PDF_GUARD_ENABLED="true",ENABLE_NOISE_FILTERS="true",INTAKE_GCS_BUCKET="$INTAKE_GCS_BUCKET",OUTPUT_GCS_BUCKET="$OUTPUT_GCS_BUCKET",SUMMARY_BUCKET="$SUMMARY_BUCKET",APP_VERSION="${APP_VERSION}",USE_REFACTORED_SUMMARISER="${USE_REFACTORED_SUMMARISER:-true}" \
  --update-secrets=OPENAI_API_KEY=${OPENAI_API_SECRET_NAME}:latest,INTERNAL_EVENT_TOKEN=${INTERNAL_EVENT_SECRET_NAME}:latest,SERVICE_ACCOUNT_JSON=${SERVICE_ACCOUNT_SECRET_NAME}:latest,${GOOGLE_APPLICATION_CREDENTIALS_MOUNT}=${GOOGLE_APPLICATION_CREDENTIALS_SECRET_NAME}:latest \
  --command uvicorn --args "src.main:create_app --factory --host 0.0.0.0 --port 8080"

echo "Deployment complete." >&2

if [[ -n "${VALIDATION_BASE_URL:-}" && -n "${VALIDATION_SOURCE_FILE_ID:-}" ]]; then
  echo "Running post-deploy PDF validation via ${VALIDATION_BASE_URL} for ${VALIDATION_SOURCE_FILE_ID}" >&2
  VALIDATION_CREDS="${VALIDATION_CREDENTIALS:-$GOOGLE_APPLICATION_CREDENTIALS}"
  python3 scripts/validate_summary.py \
    --base-url "$VALIDATION_BASE_URL" \
    --source-file-id "$VALIDATION_SOURCE_FILE_ID" \
    --credentials "$VALIDATION_CREDS" \
    ${VALIDATION_REPORT_FILE_ID:+--report-file-id "$VALIDATION_REPORT_FILE_ID"} \
    ${VALIDATION_IMPERSONATION_USER:+--impersonate "$VALIDATION_IMPERSONATION_USER"} \
    ${VALIDATION_TIMEOUT_SECONDS:+--timeout "$VALIDATION_TIMEOUT_SECONDS"} \
    ${VALIDATION_EXPECTED_PAGES:+--expected-pages "$VALIDATION_EXPECTED_PAGES"}
fi
